### ISSUE TITLE
[Feature]: 坐标过大导致bds假死

### ISSUE THREAD

**Issue by XiaoXiaoYang233** [LiteLDev/LeviAntiCheat#1]
### Is your feature request related to a problem? Please describe.

大概在1.19还是1.20的时候，当时只用了bds自带的反作弊，然后当时叫了个人测挂，他直接把自己tp到15亿格，应该是15亿，他自己说的，忘记了，总之坐标非常长，然后bds就直接假死掉了，他一旦进服bds就假死，后来装了fac了之后进服会提示发送崩服包，也就是解决了这个问题，希望lac也能解决。

### Describe the solution you'd like

对该问题解决

**Comment by Yuisyuu** [comment]
need more info

**Comment by ShrBox** [comment]
在1.20.73就算在没有LAC且关闭BDS自带反作弊的情况下也无法做到这件事

**Comment by PA733** [comment]
可以参考[这个教程](https://www.minebbs.com/resources/bds.3444/)，把对应玩家崩服时发送的数据包捕获下来，然后带附件进行反馈。

**Comment by ShrBox** [comment]
> 可以参考[这个教程](https://www.minebbs.com/resources/bds.3444/)，把对应玩家崩服时发送的数据包捕获下来，然后带附件进行反馈。

这个修复在早期的LL2中内置，后期删除了，问题是根本不可能在新版本中做到这件事，如果是因为老存档的话倒不如用存档编辑器清数据
