### ISSUE TITLE
[Feature]: 个性化功能

### ISSUE THREAD

**Issue by EpsilonZunsat** [LiteLDev/LeviAntiCheat#2]
### Is your feature request related to a problem? Please describe.

None

### Describe the solution you'd like

1.反作弊白名单系统
2.反脏话广告

**Comment by panjj95** [comment]
反作弊白名单不就是op嘛？，如果是单独给一个白名单功能，我是不建议搞的，容易牵扯利益。

**Comment by RimuruChan** [comment]
@panjj95 这牵扯什么利益，用户怎么用是用户的事情。。做这个功能是为了拆分权限，这样我是支持的。

**Comment by Tsubasa6848** [comment]
> ### Is your feature request related to a problem? Please describe.
> None
> 
> ### Describe the solution you'd like
> 1.反作弊白名单系统 2.反脏话广告
> 
> ### Describe alternatives you've considered
> _No response_
> 
> ### Additional context
> _No response_

脏话广告不应该聊天插件去管吗？
白名单系统肯定是需要的，但是这种东西如果我们内置，根本不可能满足全部人的需求，我的建议是，外置惩罚系统里面自己实现
