### ISSUE TITLE
[Bug]: 插件指令获得附魔物品附魔被清空

### ISSUE THREAD

**Issue by Gyscx** [LiteLDev/LeviAntiCheat#3]
### Describe the bug

当我使用插件指令给予自己锋利10耐久20的钻石剑后，拿到的是不带附魔的插件

### To Reproduce

配置文件铁砧附魔关，反附魔中锋利最高等级100，耐久最高32767

### Expected behavior

1

### Screenshots

1

### Platform

window10

### BDS Version

1.20.72

### LeviLamina Version

LL3 0.11.1 lse 0.6.2

### Version

beta版

### Additional context

1

**Comment by Tsubasa6848** [comment]
无法复现
