### ISSUE TITLE
[Bug]: 区块边缘的方块实体不显示

### ISSUE THREAD

**Issue by Yuisyuu** [LiteLDev/LeviAntiCheat#4]
### Describe the bug

当某个箱子位于区块边缘（与x轴与z轴无关）时，极有可能会不显示
箱子的物品不会丢失，但是无法正常点击打开
并且 当点击这个箱子后 在退出服务器之前无法正常打开容器

### To Reproduce

无

### Expected behavior

无

### Screenshots

![IMG_0741](https://github.com/LiteLDev/LeviAntiCheat/assets/100036558/444c7b56-a1b5-4965-b3d4-82a4874ed120)

### Platform

Windows

### BDS Version

1.20.73.01

### LeviLamina Version

0.11.1

### Version

0.1.3

### Additional context

[Source](http://srcld.top:35976/trace/show_bug.cgi?id=24)

**Comment by yufengya0420** [comment]
不止是箱子，区块边缘的其他方块也会不显示

**Comment by USS-LongIsland** [comment]
same
bds1.20.81.01(ProtocolVersion 671) with LeviLamina-0.12.3+032fa4e52
version 0.2.3

**Comment by USS-LongIsland** [comment]
> same bds1.20.81.01(ProtocolVersion 671) with LeviLamina-0.12.3+032fa4e52 version 0.2.3

尝试关闭antixray后似乎正常了

**Comment by KawaiiNahida** [comment]
无法复现 请问是否能找到稳定复现的方式

**Comment by USS-LongIsland** [comment]
最新release0.2.4已经好了
