### ISSUE TITLE
[Bug]: 炸掉方块后出现假方块

### ISSUE THREAD

**Issue by luckyoldboy** [LiteLDev/LeviAntiCheat#8]
### Describe the bug

用TNT炸掉会出现假方块，重进则恢复

### To Reproduce

出现问题在y轴高大概67以下，用TNT炸会出现部分假方块

### Expected behavior

无

### Platform

win11

### BDS Version

1.20.72

### LeviLamina Version

0.11.1

### Version

0.1.4

**Comment by ShrBox** [comment]
试试0.1.5？

**Comment by luckyoldboy** [comment]
![image](https://github.com/LiteLDev/LeviAntiCheat/assets/66295939/620d1a7e-e6fd-4b71-bfe6-a903db7b125a)
炸了之后，直接出现假矿方块

**Comment by ShrBox** [comment]
0.2.2还能触发吗？

**Comment by luckyoldboy** [comment]
![image](https://github.com/LiteLDev/LeviAntiCheat/assets/66295939/7844a6ab-b972-4fb1-8bd4-77d0ff13a22e)
区块边缘偶尔会出现假矿，难复现

**Comment by luckyoldboy** [comment]
![image](https://github.com/LiteLDev/LeviAntiCheat/assets/66295939/625f1344-05d3-4270-b0f4-1842f3ea4691)

**Comment by ShrBox** [comment]
0.2.3似乎修复了这个问题

**Comment by luckyoldboy** [comment]
还是会出现

**Comment by KawaiiNahida** [comment]
![ApplicationFrameHost_oE92rSVunS](https://github.com/LiteLDev/LeviAntiCheat/assets/42824603/7a1aaeeb-09e7-4e6e-a238-d456923f2241)
没法复现 是否有其他插件会拦截方块破坏

**Comment by luckyoldboy** [comment]
这个问题修复了，另一个问题是下矿过程中偶尔会出现侧墙有假矿，
![image](https://github.com/LiteLDev/LeviAntiCheat/assets/66295939/586d16fc-90b3-4cdf-a061-71b2348121df)
触发概率较小，很少能看见

**Comment by KawaiiNahida** [comment]
> 这个问题修复了，另一个问题是下矿过程中偶尔会出现侧墙有假矿， ![image](https://private-user-images.githubusercontent.com/66295939/328607180-586d16fc-90b3-4cdf-a061-71b2348121df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNDA3OTksIm5iZiI6MTcxNTE0MDQ5OSwicGF0aCI6Ii82NjI5NTkzOS8zMjg2MDcxODAtNTg2ZDE2ZmMtOTBiMy00Y2RmLWEwNjEtNzFiMjM0ODEyMWRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDAzNTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYjJmMGI3ZGMwYjU2ZDQ1N2Q4NTY2ZjJkM2MzMjk2YTFlM2U1ZWU0ZTc3ODMyYzY4Nzk0Mzc5NWFjODc1MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zylMki-RB9tqyvCU0cHyJYsk0ZGjK7COp3ikk9flduc) 触发概率较小，很少能看见

最新commit已修复 请等待更新
