### ISSUE TITLE
[Bug]: 就是崩

### ISSUE THREAD

**Issue by XSLG123** [LiteLDev/LeviAntiCheat#9]
### Describe the bug

[minidump_2024-05-02_13-16-52.dmp](https://github.com/LiteLDev/LeviAntiCheat/files/15187050/minidump_2024-05-02_13-16-52.dmp)
[trace_2024-05-02_13-18-43.log](https://github.com/LiteLDev/LeviAntiCheat/files/15187056/trace_2024-05-02_13-18-43.log)
[trace_2024-05-02_13-33-58.log](https://github.com/LiteLDev/LeviAntiCheat/files/15187057/trace_2024-05-02_13-33-58.log)

### To Reproduce

[minidump_2024-05-02_13-18-43.dmp](https://github.com/LiteLDev/LeviAntiCheat/files/15187052/minidump_2024-05-02_13-18-43.dmp)
[minidump_2024-05-02_13-33-58.dmp](https://github.com/LiteLDev/LeviAntiCheat/files/15187053/minidump_2024-05-02_13-33-58.dmp)
[trace_2024-05-02_13-16-52.log](https://github.com/LiteLDev/LeviAntiCheat/files/15187054/trace_2024-05-02_13-16-52.log)

### Expected behavior

看看咋回事

### Platform

windows10

### BDS Version

1.20.81

### LeviLamina Version

12.2

### Version

2.0.0

**Comment by ShrBox** [comment]
尝试关闭`uiItemDuplicateFix`

**Comment by Yuisyuu** [comment]
关闭DecoratedPotLootTableFix

**Comment by Yuisyuu** [comment]
已修复，请等待新版本发行
